/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.cNL.CNLPackage;
import org.xtext.example.cNL.DeclSent;
import org.xtext.example.cNL.Expression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Decl Sent</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cNL.impl.DeclSentImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cNL.impl.DeclSentImpl#getSentenceDeclaration <em>Sentence Declaration</em>}</li>
 *   <li>{@link org.xtext.example.cNL.impl.DeclSentImpl#getLogicExpression <em>Logic Expression</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeclSentImpl extends SentDeclarationImpl implements DeclSent
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getSentenceDeclaration() <em>Sentence Declaration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSentenceDeclaration()
   * @generated
   * @ordered
   */
  protected static final String SENTENCE_DECLARATION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSentenceDeclaration() <em>Sentence Declaration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSentenceDeclaration()
   * @generated
   * @ordered
   */
  protected String sentenceDeclaration = SENTENCE_DECLARATION_EDEFAULT;

  /**
   * The cached value of the '{@link #getLogicExpression() <em>Logic Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLogicExpression()
   * @generated
   * @ordered
   */
  protected Expression logicExpression;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeclSentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CNLPackage.Literals.DECL_SENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CNLPackage.DECL_SENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSentenceDeclaration()
  {
    return sentenceDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSentenceDeclaration(String newSentenceDeclaration)
  {
    String oldSentenceDeclaration = sentenceDeclaration;
    sentenceDeclaration = newSentenceDeclaration;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CNLPackage.DECL_SENT__SENTENCE_DECLARATION, oldSentenceDeclaration, sentenceDeclaration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getLogicExpression()
  {
    return logicExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLogicExpression(Expression newLogicExpression, NotificationChain msgs)
  {
    Expression oldLogicExpression = logicExpression;
    logicExpression = newLogicExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CNLPackage.DECL_SENT__LOGIC_EXPRESSION, oldLogicExpression, newLogicExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLogicExpression(Expression newLogicExpression)
  {
    if (newLogicExpression != logicExpression)
    {
      NotificationChain msgs = null;
      if (logicExpression != null)
        msgs = ((InternalEObject)logicExpression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CNLPackage.DECL_SENT__LOGIC_EXPRESSION, null, msgs);
      if (newLogicExpression != null)
        msgs = ((InternalEObject)newLogicExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CNLPackage.DECL_SENT__LOGIC_EXPRESSION, null, msgs);
      msgs = basicSetLogicExpression(newLogicExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CNLPackage.DECL_SENT__LOGIC_EXPRESSION, newLogicExpression, newLogicExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CNLPackage.DECL_SENT__LOGIC_EXPRESSION:
        return basicSetLogicExpression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CNLPackage.DECL_SENT__NAME:
        return getName();
      case CNLPackage.DECL_SENT__SENTENCE_DECLARATION:
        return getSentenceDeclaration();
      case CNLPackage.DECL_SENT__LOGIC_EXPRESSION:
        return getLogicExpression();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CNLPackage.DECL_SENT__NAME:
        setName((String)newValue);
        return;
      case CNLPackage.DECL_SENT__SENTENCE_DECLARATION:
        setSentenceDeclaration((String)newValue);
        return;
      case CNLPackage.DECL_SENT__LOGIC_EXPRESSION:
        setLogicExpression((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CNLPackage.DECL_SENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case CNLPackage.DECL_SENT__SENTENCE_DECLARATION:
        setSentenceDeclaration(SENTENCE_DECLARATION_EDEFAULT);
        return;
      case CNLPackage.DECL_SENT__LOGIC_EXPRESSION:
        setLogicExpression((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CNLPackage.DECL_SENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case CNLPackage.DECL_SENT__SENTENCE_DECLARATION:
        return SENTENCE_DECLARATION_EDEFAULT == null ? sentenceDeclaration != null : !SENTENCE_DECLARATION_EDEFAULT.equals(sentenceDeclaration);
      case CNLPackage.DECL_SENT__LOGIC_EXPRESSION:
        return logicExpression != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", sentenceDeclaration: ");
    result.append(sentenceDeclaration);
    result.append(')');
    return result.toString();
  }

} //DeclSentImpl
