/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.cNL.CNLPackage;
import org.xtext.example.cNL.DelFin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Del Fin</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DelFinImpl extends MinimalEObjectImpl.Container implements DelFin
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DelFinImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CNLPackage.Literals.DEL_FIN;
  }

} //DelFinImpl
