/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.cNL.CNLPackage;
import org.xtext.example.cNL.SentDeclaration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sent Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SentDeclarationImpl extends MinimalEObjectImpl.Container implements SentDeclaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SentDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CNLPackage.Literals.SENT_DECLARATION;
  }

} //SentDeclarationImpl
