/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.parser.antlr.internal.InternalCNLParser;
import org.xtext.example.services.CNLGrammarAccess;

public class CNLParser extends AbstractAntlrParser {

	@Inject
	private CNLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCNLParser createParser(XtextTokenStream stream) {
		return new InternalCNLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public CNLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CNLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
