/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCNLScopeProvider extends DelegatingScopeProvider {
}
