/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.ide.contentassist.antlr.internal.InternalCNLParser;
import org.xtext.example.services.CNLGrammarAccess;

public class CNLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CNLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CNLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRequirementAccess().getAlternatives(), "rule__Requirement__Alternatives");
			builder.put(grammarAccess.getTrigAccess().getAlternatives_1(), "rule__Trig__Alternatives_1");
			builder.put(grammarAccess.getTrigAccess().getAlternatives_2(), "rule__Trig__Alternatives_2");
			builder.put(grammarAccess.getInvAccess().getAlternatives_1(), "rule__Inv__Alternatives_1");
			builder.put(grammarAccess.getRelReaAccess().getAlternatives(), "rule__RelRea__Alternatives");
			builder.put(grammarAccess.getDelFinAccess().getAlternatives_1(), "rule__DelFin__Alternatives_1");
			builder.put(grammarAccess.getDelFinAccess().getAlternatives_1_0_1(), "rule__DelFin__Alternatives_1_0_1");
			builder.put(grammarAccess.getTrigAccess().getGroup(), "rule__Trig__Group__0");
			builder.put(grammarAccess.getTrigAccess().getGroup_1_0(), "rule__Trig__Group_1_0__0");
			builder.put(grammarAccess.getInvAccess().getGroup(), "rule__Inv__Group__0");
			builder.put(grammarAccess.getInvAccess().getGroup_1_0(), "rule__Inv__Group_1_0__0");
			builder.put(grammarAccess.getInvAccess().getGroup_1_0_3(), "rule__Inv__Group_1_0_3__0");
			builder.put(grammarAccess.getInvAccess().getGroup_1_1(), "rule__Inv__Group_1_1__0");
			builder.put(grammarAccess.getInv_alwaysAccess().getGroup(), "rule__Inv_always__Group__0");
			builder.put(grammarAccess.getInv_alwaysAccess().getGroup_1(), "rule__Inv_always__Group_1__0");
			builder.put(grammarAccess.getRelReaAccess().getGroup_0(), "rule__RelRea__Group_0__0");
			builder.put(grammarAccess.getRelReaAccess().getGroup_0_1(), "rule__RelRea__Group_0_1__0");
			builder.put(grammarAccess.getRelReaAccess().getGroup_0_1_10(), "rule__RelRea__Group_0_1_10__0");
			builder.put(grammarAccess.getRelReaAccess().getGroup_1(), "rule__RelRea__Group_1__0");
			builder.put(grammarAccess.getRelReaAccess().getGroup_1_1(), "rule__RelRea__Group_1_1__0");
			builder.put(grammarAccess.getRelReaAccess().getGroup_2(), "rule__RelRea__Group_2__0");
			builder.put(grammarAccess.getRelReaAccess().getGroup_2_1(), "rule__RelRea__Group_2_1__0");
			builder.put(grammarAccess.getRelReaAccess().getGroup_2_1_5(), "rule__RelRea__Group_2_1_5__0");
			builder.put(grammarAccess.getRelReaAccess().getGroup_3(), "rule__RelRea__Group_3__0");
			builder.put(grammarAccess.getRelReaAccess().getGroup_3_1(), "rule__RelRea__Group_3_1__0");
			builder.put(grammarAccess.getRelReaAccess().getGroup_3_1_6(), "rule__RelRea__Group_3_1_6__0");
			builder.put(grammarAccess.getDelFinAccess().getGroup(), "rule__DelFin__Group__0");
			builder.put(grammarAccess.getDelFinAccess().getGroup_1_0(), "rule__DelFin__Group_1_0__0");
			builder.put(grammarAccess.getDelFinAccess().getGroup_1_0_0(), "rule__DelFin__Group_1_0_0__0");
			builder.put(grammarAccess.getDelFinAccess().getGroup_1_0_1_0(), "rule__DelFin__Group_1_0_1_0__0");
			builder.put(grammarAccess.getDelFinAccess().getGroup_1_0_1_0_4(), "rule__DelFin__Group_1_0_1_0_4__0");
			builder.put(grammarAccess.getDelFinAccess().getGroup_1_0_1_1(), "rule__DelFin__Group_1_0_1_1__0");
			builder.put(grammarAccess.getDelFinAccess().getGroup_1_1(), "rule__DelFin__Group_1_1__0");
			builder.put(grammarAccess.getModelAccess().getRequirementsAssignment(), "rule__Model__RequirementsAssignment");
			builder.put(grammarAccess.getRequirementAccess().getTriggerAssignment_0(), "rule__Requirement__TriggerAssignment_0");
			builder.put(grammarAccess.getRequirementAccess().getInvariantAssignment_1(), "rule__Requirement__InvariantAssignment_1");
			builder.put(grammarAccess.getTrigAccess().getTrigAssignment_1_0_2(), "rule__Trig__TrigAssignment_1_0_2");
			builder.put(grammarAccess.getTrigAccess().getInvariantAssignment_2_0(), "rule__Trig__InvariantAssignment_2_0");
			builder.put(grammarAccess.getTrigAccess().getRelease_reactionAssignment_2_1(), "rule__Trig__Release_reactionAssignment_2_1");
			builder.put(grammarAccess.getTrigAccess().getDelay_finalAssignment_2_2(), "rule__Trig__Delay_finalAssignment_2_2");
			builder.put(grammarAccess.getInvAccess().getInvAssignment_1_0_1(), "rule__Inv__InvAssignment_1_0_1");
			builder.put(grammarAccess.getInvAccess().getDelay_finalAssignment_1_0_3_2(), "rule__Inv__Delay_finalAssignment_1_0_3_2");
			builder.put(grammarAccess.getInvAccess().getInvAssignment_1_1_1(), "rule__Inv__InvAssignment_1_1_1");
			builder.put(grammarAccess.getInvAccess().getRelease_reactionAssignment_1_1_7(), "rule__Inv__Release_reactionAssignment_1_1_7");
			builder.put(grammarAccess.getInv_alwaysAccess().getInvAssignment_1_1(), "rule__Inv_always__InvAssignment_1_1");
			builder.put(grammarAccess.getInv_alwaysAccess().getRelease_reactionAssignment_1_8(), "rule__Inv_always__Release_reactionAssignment_1_8");
			builder.put(grammarAccess.getRelReaAccess().getRelAssignment_0_1_2(), "rule__RelRea__RelAssignment_0_1_2");
			builder.put(grammarAccess.getRelReaAccess().getReaAssignment_0_1_8(), "rule__RelRea__ReaAssignment_0_1_8");
			builder.put(grammarAccess.getRelReaAccess().getDelay_finalAssignment_0_1_10_1(), "rule__RelRea__Delay_finalAssignment_0_1_10_1");
			builder.put(grammarAccess.getRelReaAccess().getRelAssignment_1_1_1(), "rule__RelRea__RelAssignment_1_1_1");
			builder.put(grammarAccess.getRelReaAccess().getReaAssignment_2_1_3(), "rule__RelRea__ReaAssignment_2_1_3");
			builder.put(grammarAccess.getRelReaAccess().getDelay_finalAssignment_2_1_5_1(), "rule__RelRea__Delay_finalAssignment_2_1_5_1");
			builder.put(grammarAccess.getRelReaAccess().getReaAssignment_3_1_4(), "rule__RelRea__ReaAssignment_3_1_4");
			builder.put(grammarAccess.getRelReaAccess().getDelay_finalAssignment_3_1_6_1(), "rule__RelRea__Delay_finalAssignment_3_1_6_1");
			builder.put(grammarAccess.getDelFinAccess().getDelAssignment_1_0_1_0_2(), "rule__DelFin__DelAssignment_1_0_1_0_2");
			builder.put(grammarAccess.getDelFinAccess().getFinAssignment_1_0_1_0_4_2(), "rule__DelFin__FinAssignment_1_0_1_0_4_2");
			builder.put(grammarAccess.getDelFinAccess().getFinAssignment_1_0_1_1_3(), "rule__DelFin__FinAssignment_1_0_1_1_3");
			builder.put(grammarAccess.getDelFinAccess().getFinAssignment_1_1_1(), "rule__DelFin__FinAssignment_1_1_1");
			builder.put(grammarAccess.getSentenceAccess().getIdsAssignment(), "rule__Sentence__IdsAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CNLGrammarAccess grammarAccess;

	@Override
	protected InternalCNLParser createParser() {
		InternalCNLParser result = new InternalCNLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CNLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CNLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
