/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cNL.AndExpression#getAndOp <em>And Op</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cNL.CNLPackage#getAndExpression()
 * @model
 * @generated
 */
public interface AndExpression extends XorExpression
{
  /**
   * Returns the value of the '<em><b>And Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>And Op</em>' attribute.
   * @see #setAndOp(String)
   * @see org.xtext.example.cNL.CNLPackage#getAndExpression_AndOp()
   * @model
   * @generated
   */
  String getAndOp();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.AndExpression#getAndOp <em>And Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>And Op</em>' attribute.
   * @see #getAndOp()
   * @generated
   */
  void setAndOp(String value);

} // AndExpression
