/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Del</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cNL.Del#getDel <em>Del</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cNL.CNLPackage#getDel()
 * @model
 * @generated
 */
public interface Del extends Delay
{
  /**
   * Returns the value of the '<em><b>Del</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Del</em>' attribute.
   * @see #setDel(String)
   * @see org.xtext.example.cNL.CNLPackage#getDel_Del()
   * @model
   * @generated
   */
  String getDel();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.Del#getDel <em>Del</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Del</em>' attribute.
   * @see #getDel()
   * @generated
   */
  void setDel(String value);

} // Del
