/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Del Fin</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.cNL.CNLPackage#getDelFin()
 * @model
 * @generated
 */
public interface DelFin extends EObject
{
} // DelFin
