/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cNL.PrimaryExpression#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cNL.PrimaryExpression#getConstant <em>Constant</em>}</li>
 *   <li>{@link org.xtext.example.cNL.PrimaryExpression#getTau <em>Tau</em>}</li>
 *   <li>{@link org.xtext.example.cNL.PrimaryExpression#getNestExpr <em>Nest Expr</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cNL.CNLPackage#getPrimaryExpression()
 * @model
 * @generated
 */
public interface PrimaryExpression extends UnExpression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(VarDeclaration)
   * @see org.xtext.example.cNL.CNLPackage#getPrimaryExpression_Name()
   * @model
   * @generated
   */
  VarDeclaration getName();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.PrimaryExpression#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(VarDeclaration value);

  /**
   * Returns the value of the '<em><b>Constant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' attribute.
   * @see #setConstant(String)
   * @see org.xtext.example.cNL.CNLPackage#getPrimaryExpression_Constant()
   * @model
   * @generated
   */
  String getConstant();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.PrimaryExpression#getConstant <em>Constant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant</em>' attribute.
   * @see #getConstant()
   * @generated
   */
  void setConstant(String value);

  /**
   * Returns the value of the '<em><b>Tau</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tau</em>' containment reference.
   * @see #setTau(TauExpression)
   * @see org.xtext.example.cNL.CNLPackage#getPrimaryExpression_Tau()
   * @model containment="true"
   * @generated
   */
  TauExpression getTau();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.PrimaryExpression#getTau <em>Tau</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tau</em>' containment reference.
   * @see #getTau()
   * @generated
   */
  void setTau(TauExpression value);

  /**
   * Returns the value of the '<em><b>Nest Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nest Expr</em>' containment reference.
   * @see #setNestExpr(Expression)
   * @see org.xtext.example.cNL.CNLPackage#getPrimaryExpression_NestExpr()
   * @model containment="true"
   * @generated
   */
  Expression getNestExpr();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.PrimaryExpression#getNestExpr <em>Nest Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nest Expr</em>' containment reference.
   * @see #getNestExpr()
   * @generated
   */
  void setNestExpr(Expression value);

} // PrimaryExpression
