/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cNL.Rel#getRel <em>Rel</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cNL.CNLPackage#getRel()
 * @model
 * @generated
 */
public interface Rel extends RelRea
{
  /**
   * Returns the value of the '<em><b>Rel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rel</em>' reference.
   * @see #setRel(SentenceDeclaration)
   * @see org.xtext.example.cNL.CNLPackage#getRel_Rel()
   * @model
   * @generated
   */
  SentenceDeclaration getRel();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.Rel#getRel <em>Rel</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rel</em>' reference.
   * @see #getRel()
   * @generated
   */
  void setRel(SentenceDeclaration value);

} // Rel
