/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Requirement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cNL.Requirement#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link org.xtext.example.cNL.Requirement#getInvariant <em>Invariant</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cNL.CNLPackage#getRequirement()
 * @model
 * @generated
 */
public interface Requirement extends EObject
{
  /**
   * Returns the value of the '<em><b>Trigger</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger</em>' containment reference.
   * @see #setTrigger(Trig)
   * @see org.xtext.example.cNL.CNLPackage#getRequirement_Trigger()
   * @model containment="true"
   * @generated
   */
  Trig getTrigger();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.Requirement#getTrigger <em>Trigger</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger</em>' containment reference.
   * @see #getTrigger()
   * @generated
   */
  void setTrigger(Trig value);

  /**
   * Returns the value of the '<em><b>Invariant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invariant</em>' containment reference.
   * @see #setInvariant(Inv_always)
   * @see org.xtext.example.cNL.CNLPackage#getRequirement_Invariant()
   * @model containment="true"
   * @generated
   */
  Inv_always getInvariant();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.Requirement#getInvariant <em>Invariant</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Invariant</em>' containment reference.
   * @see #getInvariant()
   * @generated
   */
  void setInvariant(Inv_always value);

} // Requirement
