/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cNL.Sentence#getDelay <em>Delay</em>}</li>
 *   <li>{@link org.xtext.example.cNL.Sentence#getFin <em>Fin</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cNL.CNLPackage#getSentence()
 * @model
 * @generated
 */
public interface Sentence extends DelFin
{
  /**
   * Returns the value of the '<em><b>Delay</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delay</em>' containment reference.
   * @see #setDelay(Delay)
   * @see org.xtext.example.cNL.CNLPackage#getSentence_Delay()
   * @model containment="true"
   * @generated
   */
  Delay getDelay();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.Sentence#getDelay <em>Delay</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delay</em>' containment reference.
   * @see #getDelay()
   * @generated
   */
  void setDelay(Delay value);

  /**
   * Returns the value of the '<em><b>Fin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fin</em>' attribute.
   * @see #setFin(String)
   * @see org.xtext.example.cNL.CNLPackage#getSentence_Fin()
   * @model
   * @generated
   */
  String getFin();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.Sentence#getFin <em>Fin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fin</em>' attribute.
   * @see #getFin()
   * @generated
   */
  void setFin(String value);

} // Sentence
