/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sentence Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cNL.SentenceDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cNL.SentenceDeclaration#getLogicExpression <em>Logic Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cNL.CNLPackage#getSentenceDeclaration()
 * @model
 * @generated
 */
public interface SentenceDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.cNL.CNLPackage#getSentenceDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.SentenceDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Logic Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logic Expression</em>' containment reference.
   * @see #setLogicExpression(Expression)
   * @see org.xtext.example.cNL.CNLPackage#getSentenceDeclaration_LogicExpression()
   * @model containment="true"
   * @generated
   */
  Expression getLogicExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.SentenceDeclaration#getLogicExpression <em>Logic Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logic Expression</em>' containment reference.
   * @see #getLogicExpression()
   * @generated
   */
  void setLogicExpression(Expression value);

} // SentenceDeclaration
