/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sent Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cNL.SentDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cNL.SentDeclaration#getSentenceDeclaration <em>Sentence Declaration</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cNL.CNLPackage#getSentDeclaration()
 * @model
 * @generated
 */
public interface SentDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.cNL.CNLPackage#getSentDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.SentDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Sentence Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sentence Declaration</em>' containment reference.
   * @see #setSentenceDeclaration(SentenceDeclaration)
   * @see org.xtext.example.cNL.CNLPackage#getSentDeclaration_SentenceDeclaration()
   * @model containment="true"
   * @generated
   */
  SentenceDeclaration getSentenceDeclaration();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.SentDeclaration#getSentenceDeclaration <em>Sentence Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sentence Declaration</em>' containment reference.
   * @see #getSentenceDeclaration()
   * @generated
   */
  void setSentenceDeclaration(SentenceDeclaration value);

} // SentDeclaration
