/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Un Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cNL.UnExpression#getUnOp <em>Un Op</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cNL.CNLPackage#getUnExpression()
 * @model
 * @generated
 */
public interface UnExpression extends EquExpression
{
  /**
   * Returns the value of the '<em><b>Un Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Un Op</em>' attribute.
   * @see #setUnOp(String)
   * @see org.xtext.example.cNL.CNLPackage#getUnExpression_UnOp()
   * @model
   * @generated
   */
  String getUnOp();

  /**
   * Sets the value of the '{@link org.xtext.example.cNL.UnExpression#getUnOp <em>Un Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Un Op</em>' attribute.
   * @see #getUnOp()
   * @generated
   */
  void setUnOp(String value);

} // UnExpression
