/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cNL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Xor Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.cNL.CNLPackage#getXorExpression()
 * @model
 * @generated
 */
public interface XorExpression extends Expression
{
} // XorExpression
